import math
WIDTH = 840
HEIGHT = 500
HALF_WIDTH = WIDTH //  2
HALF_HEIGHT = HEIGHT //  2
pos_player = (HALF_WIDTH, HALF_HEIGHT)
TILE = 50

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 120
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / ( 2 * math.tan(HALF_FOV) )
PROJ_COEFF = 3 * DIST *TILE
SCALE = WIDTH // NUM_RAYS

# min map
MAP_SCALE = 5
MAP_TILE = TILE // MAP_SCALE
MAP_POS = (0, HEIGHT - HEIGHT // MAP_SCALE)